### ISSUE TITLE
Making Flexmi YAML flavour more natural

### ISSUE THREAD

**Issue by agarciadom** [eclipse/epsilon#21]
I tried writing some Flexmi files in YAML format today, using this custom Metamodeling:

[queryset-metamodel.zip](https://github.com/eclipse/epsilon/files/10155016/queryset-metamodel.zip)

I tried writing this bit:

```yaml
?nsuri: https://eclipse.org/hawk/sqlite/queries
queryset:
  name: NonTimeawareQueries
  queries:
    - name: "nodeIDsByLabel"
      sql: "SELECT rowid FROM nodes WHERE label = ?;"
      parameters:
        - name: label
          type: String
    - name: "nodeCountByLabelStatement"
      sql: "SELECT COUNT(1) FROM nodes WHERE label = ?;"
      parameters:
        - name: label
          type: String
```

I expected to see one QuerySet with its proper name and two queries, each with their own name and parameters. This is in line with typical use of YAML, which supports three types of nodes: maps (essentially, objects), sequences (lists), and scalar values. I had expected to see maps turned into objects, sequences turned into ELists, and scalar values to be used to set attributes / references.

Unfortunately, I got something rather odd instead:

![image](https://user-images.githubusercontent.com/46504/205663319-9b703dd6-b884-4ddb-bde3-d0cb79bdcbfe.png)

I had one Query with two parameters, for some reason.

I had to change the YAML file to this, which is cumbersome to type with all the `-`s, and it's also not natural YAML:

```yaml
?nsuri: https://eclipse.org/hawk/sqlite/queries
queryset:
  - name: NonTimeawareQueries
  - query:
    - name: "nodeIDsByLabel"
    - sql: "SELECT rowid FROM nodes WHERE label = ?;"
    - parameters:
        - name: label
        - type: String
  - query:
    - name: "nodeCountByLabelStatement"
    - sql: "SELECT COUNT(1) FROM nodes WHERE label = ?;"
    - parameters:
        - name: label
        - type: String
```

That produced the expected outline:

![image](https://user-images.githubusercontent.com/46504/205664058-5fc4824d-f6f5-44d0-9cd7-c2f5ab4addf1.png)

From a semantic point of view, it doesn't make sense to have `queryset` need to contain a list with its first element being a map whose key is `name` just to set the name of that queryset. Same goes for specifying its child objects.

**Comment by agarciadom** [comment]
To clarify, what I mean is that it's much more natural YAML to do:

```yaml
queryset:
  name: foo
```

Than to do this:

```yaml
queryset:
  - name: foo
```

The first option says "name is a property of the queryset, which is equal to 'foo'".

The second option says "queryset contains an element whose name is 'foo'".

**Comment by agarciadom** [comment]
For comparison, I changed this to Flexmi XML just now:

```xml
<?nsuri https://eclipse.org/hawk/sqlite/queries?>
<queryset name="NonTimeawareQueries">
  <query name="nodeIDsByLabel" sql="SELECT rowid FROM nodes WHERE label = ?;">
    <param name="label" type="String"/>
  </query>
  <query name="nodeCountByLabelStatement" sql="SELECT COUNT(1) FROM nodes WHERE label = ?;">
    <param name="label" type="String"/>
  </query>
 </queryset>
```

**Comment by kolovos** [comment]
We should also use `$` instead of `?` for processing instructions in YAML as the latter has [existing semantics](https://stackoverflow.com/questions/33987316/what-is-a-complex-mapping-key-in-yaml) i.e.

`$nsuri: https://eclipse.org/hawk/sqlite/queries`

instead of 

`?nsuri: https://eclipse.org/hawk/sqlite/queries`

For backwards-compatibilty we can support both and drop support for `?` in 3.x.

**Comment by agarciadom** [comment]
Sounds good. I tried rewriting the Flexmi services example into this new version of the YAML flavour, and it'd look like this (`$type` could be used to disambiguate when the type cannot be guessed):

```yaml
$nsuri: services
$type: Model
services:
  - name: Followers
    op:
      - name: get
        in: [{name: user, type: String}]
        out: [{type: User, many: true}]
types:
  - $type: Struct
    name: User
    f:
      - {name: id, type: String}
      - {name: bio, type: String}
  - $type: Primitive
    name: String
```

**Comment by agarciadom** [comment]
With the current version of the PR (#222), which doesn't use `$type` anymore, the above example would become:

```yaml
$nsuri: services
model:
  services:
    name: Followers
    op:
      name: get
      in: {name: user, type: String}
      out: {type: User, many: true}
  types:
    struct:
      name: User
      f:
        - {name: id, type: String}
        - {name: bio, type: String}
    primitive:
      name: String
```
